### ISSUE TITLE
Suggestions for addition to nimbula / OpenStack-Folsom-Install-guide

### ISSUE THREAD

**Issue by David-P-B** [c4urself/OpenStack-Folsom-Install-guide#13]
Excellent guide, I managed to get Openstack Folsom working with Cinder and nova-network using this guide.

Suggested additions /ammendments.

1) After creating physical volume and volume group on CONTROL NODE, I think we need to start the iSCSI services. As root
$ sudo su
$ sed -i 's/false/true/g' /etc/default/iscsitarget
$ service iscsitarget start
$ service open-iscsi start

2) May need to install sysfsutils on CONTROL and COMPUTE NODES.
Not totally sure about this, but my installation only started working after trying this and several service restarts / reboots. See:
https://answers.launchpad.net/cinder/+question/222896
$ apt-get install sysfsutils

3) Floating IP always seems to start at X.X.X.1 when using Dashbaord to assign floating IP after creating a network. I could not find a floating_start config comand for nova.conf.  I used nova add-floating-ip and nova remove-floating-ip commands to assign and un-assign specific floating IP, e.g.
$ nova-manage floating create --pool=nova --ip_range=192.168.40.0/24
$ nova add-floating-ip <instance-id> 192.168.40.21
$ nova remove-floating-ip <instance-id> 192.168.40.21

4) Beginners need to know about .pem files / access and security ports for using ubuntu VM images, e.g.

Add an Ubuntu image
$ glance image-create --location http://uec-images.ubuntu.com/releases/12.04/release/ubuntu-12.04-server-cloudimg-amd64-disk1.img --is-public true --disk-format qcow2 --container-format bare --name "Ubuntu 12.04 amd64"

Enable ssh and ping in Dashbaord
Select Project Tab
Select Project=Demo etc
Access & Security / Edit Rules

IP Protocol     From Port   To Port
TCP                 22  22      0.0.0.0/0 (CIDR)  
ICMP          -1    -1      0.0.0.0/0 (CIDR)

Access & Security / Keypairs
Create keypair and download .pem file to Linux desktop PC.
$ cp ./Downloads/Keypair1.pem ./.ssh/
$ chmod 600 .ssh/*.pem
$ ssh -i .ssh/keypair1.pem ubuntu@192.168.40.21

5) When I tired to create use or create cinder volumes in the Demo or Admin projects using the Dashbaord, the volumes seemed to break. I needed to remove and then create new physical volume and volume groups to fix. Sometimes needed to edit the cinder mysql volume info as well. 
This may be something to do with tenanats, projects and creds file  that I don't know about. The only way I could get the cinder volumes to work was using the cinder and nova-volume commands on the CONTROL NODE command  line, see:
http://rconradharris.com/2013/01/14/getting-cinder-up-and-running
As root on CONTROL NODE
$ cinder create --display_name vol1 1
$ cinder list
$ nova volume-attach <instance_ID> /dev/vdb

Perform an sudo fdisk -l in the ubuntu VM instance or cinder list shows attaching and then returns to available after about 20 seconds.
ubuntu@VM1$ sudo fdisk -l
ubuntu@VM1$ sudo fdisk -l

When /dev/vdb appears need to create apartition, foramt the partition and mount the storage.

ubuntu@VM1$ sudo su
root@VM1$ fdisk /dev/vdb
    d
    ENTER
    n
    p
    1
    ENTER
    ENTER
    w

root@VM1$ apt-get install xfsprogs
root@VM1$ mkfs.xfs /dev/vdb1
root@VM1$ mkdir /mnt/store
root@VM1$ mount -t xfs /dev/vdb1 /mnt/store
root@VM1$ chmod 777 /mnt/store

To remove volume
root@VM1$ umount /mnet/store

root@CONTROL_NODE$ nova volume-detach <instance_ID> /dev/vdb

**Comment by nemo97** [comment]
Thanks for contribution. I just installed yesterday and seems like working. But I am not able to create volume from dashboard and after going through this post seems like will resolve my problem.

**Comment by zachvanduyn** [comment]
@David-P-B 

Awesome, thank you for the notes. It looks like we could definitely expand and improve a few areas of the current guide. I'm currently bogged down with University classes and am about to begin an internship. Give me a few weeks to settle things back down. After that, I'd love to sift through and polish a few of these ideas so they can be merged into the guide.
