### ISSUE TITLE
error when executing keystone_basic.sh

### ISSUE THREAD

**Issue by hp-data** [c4urself/OpenStack-Folsom-Install-guide#7]
Here is what I am getting when attempting to run the basic script...

Can you please help me solve this, thanks in advance

 ./keystone_basic.sh 
No handlers could be found for logger "keystoneclient.client"
Conflict occurred attempting to store tenant. (IntegrityError) (1062, "Duplicate entry 'admin' for key 'name'") 'INSERT INTO tenant (id, name, extra) VALUES (%s, %s, %s)' ('e834fd7070ef4f9aaf4cfa0c3b6cf632', 'admin', '{"enabled": true, "description": null}') (HTTP 409)
No handlers could be found for logger "keystoneclient.client"
Conflict occurred attempting to store tenant. (IntegrityError) (1062, "Duplicate entry 'service' for key 'name'") 'INSERT INTO tenant (id, name, extra) VALUES (%s, %s, %s)' ('25625fd6334a41a5a449ee10e806ad6f', 'service', '{"enabled": true, "description": null}') (HTTP 409)
No handlers could be found for logger "keystoneclient.client"
Conflict occurred attempting to store user. (IntegrityError) (1062, "Duplicate entry 'admin' for key 'name'") 'INSERT INTO user (id, name, extra) VALUES (%s, %s, %s)' ('3054854469f4444b9d2fa80ac0c85a0b', 'admin', '{"password": "$6$rounds=40000$MzguFnnXsVPS4zs6$.iIFRXGegek9XTpXH2KGcH/lJTATSniPMWi/QRoIa6oE96VOYjMOXV3P3G4.umIifweqA1aTU6KZ5uzJ7MI9p1", "enabled": true, "email": "admin@domain.com", "tenantId": null}') (HTTP 409)
No handlers could be found for logger "keystoneclient.client"
Conflict occurred attempting to store role. (IntegrityError) (1062, "Duplicate entry 'admin' for key 'name'") 'INSERT INTO role (id, name) VALUES (%s, %s)' ('0af01aa38f1345cba2e75ba04b922666', 'admin') (HTTP 409)
No handlers could be found for logger "keystoneclient.client"
Conflict occurred attempting to store role. (IntegrityError) (1062, "Duplicate entry 'KeystoneAdmin' for key 'name'") 'INSERT INTO role (id, name) VALUES (%s, %s)' ('2d2112943ba64cb282fcb8f042f493fa', 'KeystoneAdmin') (HTTP 409)
No handlers could be found for logger "keystoneclient.client"
Conflict occurred attempting to store role. (IntegrityError) (1062, "Duplicate entry 'KeystoneServiceAdmin' for key 'name'") 'INSERT INTO role (id, name) VALUES (%s, %s)' ('2bb6c3e24e0a44928371ce17753e8aba', 'KeystoneServiceAdmin') (HTTP 409)
usage: keystone user-role-add --user <user-id> --role <role-id>
                              [--tenant_id <tenant-id>]
keystone user-role-add: error: argument --user is required
usage: keystone user-role-add --user <user-id> --role <role-id>
                              [--tenant_id <tenant-id>]
keystone user-role-add: error: argument --user is required
usage: keystone user-role-add --user <user-id> --role <role-id>
                              [--tenant_id <tenant-id>]
keystone user-role-add: error: argument --user is required
No handlers could be found for logger "keystoneclient.client"
Conflict occurred attempting to store role. (IntegrityError) (1062, "Duplicate entry 'Member' for key 'name'") 'INSERT INTO role (id, name) VALUES (%s, %s)' ('2e19e6ad536a4ad1bb4fd9048b05cc75', 'Member') (HTTP 409)
usage: keystone [--os_username <auth-user-name>]
                [--os_password <auth-password>]
                [--os_tenant_name <auth-tenant-name>]
                [--os_tenant_id <tenant-id>] [--os_auth_url <auth-url>]
                [--os_region_name <region-name>]
                [--os_identity_api_version <identity-api-version>]
                [--token <service-token>] [--endpoint <service-endpoint>]
                [--username <auth-user-name>] [--password <auth-password>]
                [--tenant_name <tenant-name>] [--auth_url <auth-url>]
                [--region_name <region-name>]
                <subcommand> ...
keystone: error: unrecognized arguments: --tenant-id
usage: keystone user-role-add --user <user-id> --role <role-id>
                              [--tenant_id <tenant-id>]
keystone user-role-add: error: argument --user is required
usage: keystone [--os_username <auth-user-name>]
                [--os_password <auth-password>]
                [--os_tenant_name <auth-tenant-name>]
                [--os_tenant_id <tenant-id>] [--os_auth_url <auth-url>]
                [--os_region_name <region-name>]
                [--os_identity_api_version <identity-api-version>]
                [--token <service-token>] [--endpoint <service-endpoint>]
                [--username <auth-user-name>] [--password <auth-password>]
                [--tenant_name <tenant-name>] [--auth_url <auth-url>]
                [--region_name <region-name>]
                <subcommand> ...
keystone: error: unrecognized arguments: --tenant-id
usage: keystone user-role-add --user <user-id> --role <role-id>
                              [--tenant_id <tenant-id>]
keystone user-role-add: error: argument --user is required
usage: keystone [--os_username <auth-user-name>]
                [--os_password <auth-password>]
                [--os_tenant_name <auth-tenant-name>]
                [--os_tenant_id <tenant-id>] [--os_auth_url <auth-url>]
                [--os_region_name <region-name>]
                [--os_identity_api_version <identity-api-version>]
                [--token <service-token>] [--endpoint <service-endpoint>]
                [--username <auth-user-name>] [--password <auth-password>]
                [--tenant_name <tenant-name>] [--auth_url <auth-url>]
                [--region_name <region-name>]
                <subcommand> ...
keystone: error: unrecognized arguments: --tenant-id
usage: keystone user-role-add --user <user-id> --role <role-id>
                              [--tenant_id <tenant-id>]
keystone user-role-add: error: argument --user is required
usage: keystone [--os_username <auth-user-name>]
                [--os_password <auth-password>]
                [--os_tenant_name <auth-tenant-name>]
                [--os_tenant_id <tenant-id>] [--os_auth_url <auth-url>]
                [--os_region_name <region-name>]
                [--os_identity_api_version <identity-api-version>]
                [--token <service-token>] [--endpoint <service-endpoint>]
                [--username <auth-user-name>] [--password <auth-password>]
                [--tenant_name <tenant-name>] [--auth_url <auth-url>]
                [--region_name <region-name>]
                <subcommand> ...
keystone: error: unrecognized arguments: --tenant-id
usage: keystone user-role-add --user <user-id> --role <role-id>
                              [--tenant_id <tenant-id>]
keystone user-role-add: error: argument --user is required

**Comment by tatendam** [comment]
Did you remember to create an sql database for keystone before running the script and enter the correct MySQL credentials in those scripts? Check that, sometimes that is the problem.

**Comment by hp-data** [comment]
Thank you, 

I will check my steps again, I thought I created the db and passed the correct creds, but you never know

Date: Tue, 5 Feb 2013 12:51:20 -0800

**Comment by nemo97** [comment]
Since yesterday I have been tying to execute keystone_basic.sh and I was having "keystone user-role-add: error: argument --user is required". Seems like --user-id,--tenant_id & --role-id are not valid option anymore in keystone. I replaces these with --user,--tenant_id & --role and now working properly. May be something to do with keystone version !! I am using ubuntu 12.04.2 LTS server. Had to change similar changes in keystone_endpoints_basic.sh also.

**Comment by tatendam** [comment]
Yes there is a difference between the version of Ubuntu you use and the
version of OpenStack it will download from repositories. If I remember
correctly, 12.04 LTS downloads OpenStack Essex automatically unless you
change which version to download in your config files. Ubuntu Server 12.10
downloads Folsom by default. Between Essex and Folsom a lot of flags and
commands change in Keystone and Nova specifically. The script above was
meant for Folsom installs for users running Ubuntu Server 12.10. If you
considered upgrading, the install script should give you no problems at all.

Let me know if you have any other problems :)

On Tue, Apr 23, 2013 at 1:27 PM, Subhas Sing notifications@github.comwrote:

> Since yesterday I have been tying to execute keystone_basic.sh and I was
> having "keystone user-role-add: error: argument --user is required". Seems
> like --user-id,--tenant_id & --role-id are not valid option anymore in
> keystone. I replaces these with --user,--tenant_id & --role and now working
> properly. May be something to do with keystone version !! I am using ubuntu
> 12.04.2 LTS server. Had to change similar changes in
> keystone_endpoints_basic.sh also.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nimbula/OpenStack-Folsom-Install-guide/issues/7#issuecomment-16873211
> .

## 

Tatenda Mupaso
tatenda.mupaso@gmail.com
216-496-4427

**Comment by nemo97** [comment]
Thanks Tetendam! I figure it out that from url - http://docs.openstack.org/folsom/basic-install/content/basic-install_controller.html
I modify as per point 2 and it downloaded correct version and worked all the scripts as expected.Great work!
