### ISSUE TITLE
Cinder issues

### ISSUE THREAD

**Issue by juliendf** [c4urself/OpenStack-Folsom-Install-guide#9]
If you want to create Block Storage Volume : 

root@Controller01:~# service cinder-volume restart
stop: Unknown instance: 
cinder-volume start/running, process 18844

root@Controller01:~# service cinder-api restart
cinder-api stop/waiting
cinder-api start/running, process 18874

root@Controller01:~# service cinder-scheduler restart
cinder-scheduler stop/waiting
cinder-scheduler start/running, process 18904

vi /etc/default/iscsitarget
False to True

and then
/etc/init.d/iscsitarget start

Julien

**Comment by nibaojin** [comment]
Thx for your help，climz ^^

------------------ 原始邮件 ------------------
发件人: "CliMz"notifications@github.com;
发送时间: 2013年3月13日(星期三) 凌晨4:47
收件人: "nimbula/OpenStack-Folsom-Install-guide"OpenStack-Folsom-Install-guide@noreply.github.com; 

主题: [OpenStack-Folsom-Install-guide] Cinder issues (#9)

If you want to create Block Storage Volume : 

root@Controller01:~# service cinder-volume restart
 stop: Unknown instance: 
 cinder-volume start/running, process 18844

root@Controller01:~# service cinder-api restart
 cinder-api stop/waiting
 cinder-api start/running, process 18874

root@Controller01:~# service cinder-scheduler restart
 cinder-scheduler stop/waiting
 cinder-scheduler start/running, process 18904

vi /etc/default/iscsitarget
 False to True

and then
 /etc/init.d/iscsitarget start

Julien
